name: Publish

on:
  push:
    # only publish on version tags
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        path: ./android
        submodules: recursive

    - name: set up JDK 12
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt'

    - name: Download aars
      run: |
        ./downloadAar.sh
        ./downloadAar_prefixed.sh

    - name: Check required files exist
      run: |
        test -f "android/libwebrtc.aar"
        test -f "android-prefixed/shadow/libs/classes.jar"
        test -f "android-prefixed/src/main/jniLibs/arm64-v8a/liblkjingle_peerconnection_so.so"
        test -f "android-prefixed/src/main/jniLibs/armeabi-v7a/liblkjingle_peerconnection_so.so"
        test -f "android-prefixed/src/main/jniLibs/x86/liblkjingle_peerconnection_so.so"
        test -f "android-prefixed/src/main/jniLibs/x86_64/liblkjingle_peerconnection_so.so"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create gpg key and import into gradle properties
      run: |
        echo $GPG_KEY_ARMOR | base64 --decode > ./release.asc
        gpg --quiet --output $GITHUB_WORKSPACE/release.gpg --dearmor ./release.asc
        sed -i -e "s,nexusUsername=,nexusUsername=$NEXUS_USERNAME,g" gradle.properties
        sed -i -e "s,nexusPassword=,nexusPassword=$NEXUS_PASSWORD,g" gradle.properties
        sed -i -e "s,signing.keyId=,signing.keyId=$GPG_KEY_ID,g" gradle.properties
        sed -i -e "s,signing.password=,signing.password=$GPG_PASSWORD,g" gradle.properties
        sed -i -e "s,signing.secretKeyRingFile=,signing.secretKeyRingFile=$GITHUB_WORKSPACE/release.gpg,g" gradle.properties
        sed -i -e "s,STAGING_PROFILE_ID=,STAGING_PROFILE_ID=$STAGING_PROFILE_ID,g" gradle.properties
      env:
        GPG_KEY_ARMOR: ${{ secrets.SIGNING_KEY_ARMOR }}
        GPG_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        GPG_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        STAGING_PROFILE_ID: ${{ secrets.STAGING_PROFILE_ID }}

    - name: Assemble
      run: ./gradlew assemble

    - name: Publish to sonatype
      run: ./gradlew publishAllPublicationsToMavenRepository closeAndReleaseMavenStagingRepository -Dorg.gradle.parallel=false